In [15]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.model_selection import train_test_split

%matplotlib inline

In [16]:
DATA_PATH = '../data/'

In [17]:
dat = pd.read_csv(DATA_PATH + 'buyStats.csv')
dat['buyDate'] = pd.to_datetime(dat['buyDate'])
dat['sellDate'] = pd.to_datetime(dat['sellDate'])
dat.head()

,stock,bundles,buyPrice,sellPrice,change,buyDate,sellDate,nDays,d30Sell,d30Gains,...,Fid,FidBest,ohCheap,ohOut,spVal,macd,spRSI14,spPmoB75_40_20,spPmoW75_40_20,vix
0,cgnx,2,NaN,NaN,NaN,2017-07-03,NaT,-2,NaN,NaN,...,4.9,0,NaN,NaN,2423,-8.678,49.36,0.581,0.610,11.18
1,cgnx,2,90.10,NaN,NaN,2017-06-29,NaT,2,NaN,NaN,...,4.9,0,1,2.50,2441,-4.685,57.26,0.607,0.615,10.03
2,nvda,2,NaN,NaN,NaN,2017-07-03,NaT,-2,NaN,NaN,...,5.9,2,NaN,NaN,2423,-8.678,49.36,0.581,0.610,11.18
3,nvda,2,151.52,NaN,NaN,2017-06-14,NaT,17,NaN,NaN,...,6.1,2,1,2.34,2440,4.950,66.39,0.630,0.600,10.42
4,tsco,2,NaN,NaN,NaN,2017-07-03,NaT,-2,NaN,NaN,...,1.7,-1,NaN,NaN,2423,-8.678,49.36,0.581,0.610,11.18

In [18]:
d30 = dat.loc[np.isnan(dat['d30Gains']) == False, :]
d30.head()

,stock,bundles,buyPrice,sellPrice,change,buyDate,sellDate,nDays,d30Sell,d30Gains,...,Fid,FidBest,ohCheap,ohOut,spVal,macd,spRSI14,spPmoB75_40_20,spPmoW75_40_20,vix
14,odfl,1,86.87,NaN,NaN,2017-05-22,NaT,40,93.02,1.07080,...,8.1,2,2.67,2.38,2382,-8.638,NaN,NaN,NaN,12.04
21,adbe,0,131.72,143.35,1.088293,2017-04-21,2017-06-06,71,136.43,1.03576,...,7.8,1,1.33,1.72,2349,-11.600,NaN,NaN,NaN,14.20
22,ahgp,0,29.10,NaN,NaN,2017-05-22,NaT,40,23.95,0.82302,...,9.4,0,3.67,3.00,2382,-8.638,NaN,NaN,NaN,12.04
24,amrc,0,6.60,NaN,NaN,2017-05-12,NaT,50,6.85,1.03788,...,5.1,-1,3.33,1.33,2394,4.011,NaN,NaN,NaN,10.60
25,atvi,0,53.30,57.06,1.070544,2017-05-02,2017-06-12,60,59.56,1.11745,...,6.4,1,2.33,1.77,2388,5.301,NaN,NaN,NaN,10.11

In [19]:
#[(a, b) for a, b in zip(range(len(list(d30))), list(d30))]
y = d30['d30Gains']
X = d30.ix[:, 25:]
print(X.shape)
X.head()

(38, 26)

,MF,MFRisk,n_L52,n_H52,pE,pB,revG5,freeCashFlow,grossMarQ,opMarQ,...,Fid,FidBest,ohCheap,ohOut,spVal,macd,spRSI14,spPmoB75_40_20,spPmoW75_40_20,vix
14,now,8,1.515509,0.905444,64,77,84,NaN,NaN,78,...,8.1,2,2.67,2.38,2382,-8.638,NaN,NaN,NaN,12.04
21,now,9,1.457900,0.998000,NaN,NaN,NaN,NaN,NaN,NaN,...,7.8,1,1.33,1.72,2349,-11.600,NaN,NaN,NaN,14.20
22,none,NaN,1.808750,0.885015,21,73,61,96,NaN,81,...,9.4,0,3.67,3.00,2382,-8.638,NaN,NaN,NaN,12.04
24,none,NaN,1.580189,0.950355,NaN,NaN,NaN,NaN,NaN,NaN,...,5.1,-1,3.33,1.33,2394,4.011,NaN,NaN,NaN,10.60
25,start,9,1.570790,0.993777,56,45,43,98,NaN,94,...,6.4,1,2.33,1.77,2388,5.301,NaN,NaN,NaN,10.11

In [20]:
def median_fill(df):
    X = df.copy()
    
    for col in list(X):
        try:
            X[col][np.isnan(X[col])] = np.nanmedian(X[col])
        except:
            print('Could not fill column', col)
    return X

In [21]:
X = median_fill(X)
X.head()

/Users/dsp/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/dsp/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py:3858: RuntimeWarning: All-NaN slice encountered
  r = func(a, **kwargs)

('Could not fill column', 'MF')

,MF,MFRisk,n_L52,n_H52,pE,pB,revG5,freeCashFlow,grossMarQ,opMarQ,...,Fid,FidBest,ohCheap,ohOut,spVal,macd,spRSI14,spPmoB75_40_20,spPmoW75_40_20,vix
14,now,8,1.515509,0.905444,64.0,77,84,86,NaN,78,...,8.1,2,2.67,2.38,2382,-8.638,62.81,0.56,0.58,12.04
21,now,9,1.457900,0.998000,60.5,77,49,86,NaN,81,...,7.8,1,1.33,1.72,2349,-11.600,62.81,0.56,0.58,14.20
22,none,8,1.808750,0.885015,21.0,73,61,96,NaN,81,...,9.4,0,3.67,3.00,2382,-8.638,62.81,0.56,0.58,12.04
24,none,8,1.580189,0.950355,60.5,77,49,86,NaN,81,...,5.1,-1,3.33,1.33,2394,4.011,62.81,0.56,0.58,10.60
25,start,9,1.570790,0.993777,56.0,45,43,98,NaN,94,...,6.4,1,2.33,1.77,2388,5.301,62.81,0.56,0.58,10.11

In [23]:
drop_cols = ['MF', 'grossMarQ']
X = X.drop(drop_cols, axis=1)
X.head()

ValueError: labels ['MF' 'grossMarQ'] not contained in axis